INSERT INTO user_roles(ID,NAME) VALUES (1,'CLIENT');
INSERT INTO users (ID,FIRST_NAME,USER_ROLES_ID) VALUES (1,'USER1',1);
INSERT INTO users (ID,FIRST_NAME,USER_ROLES_ID) VALUES (2,'USER2',1);
INSERT INTO users (ID,FIRST_NAME,USER_ROLES_ID) VALUES (3,'USER3',1);
INSERT INTO users (ID,FIRST_NAME,USER_ROLES_ID) VALUES (4,'USER4',1);
INSERT INTO users (ID,FIRST_NAME,USER_ROLES_ID) VALUES (5,'USER5',1);
INSERT INTO users (ID,FIRST_NAME,USER_ROLES_ID) VALUES (6,'USER6',1);