INSERT INTO user_roles (ID,NAME) VALUES (1,'USER_ROLE1');
INSERT INTO user_roles (ID,NAME) VALUES (2,'USER_ROLE2');
INSERT INTO user_roles (ID,NAME) VALUES (3,'USER_ROLE3');
INSERT INTO user_roles (ID,NAME) VALUES (4,'USER_ROLE4');
INSERT INTO user_roles (ID,NAME) VALUES (5,'USER_ROLE5');
INSERT INTO user_roles (ID,NAME) VALUES (6,'USER_ROLE6');