INSERT INTO event (ID,NAME) VALUES (1,'EVENT1');
INSERT INTO event (ID,NAME) VALUES (2,'EVENT2');
INSERT INTO event (ID,NAME) VALUES (3,'EVENT3');
INSERT INTO event (ID,NAME) VALUES (4,'EVENT4');
INSERT INTO event (ID,NAME) VALUES (5,'EVENT5');
INSERT INTO event (ID,NAME) VALUES (6,'EVENT6');