INSERT INTO user (ID,FIRST_NAME) VALUES (1,'USER1');
INSERT INTO user (ID,FIRST_NAME) VALUES (2,'USER2');
INSERT INTO user (ID,FIRST_NAME) VALUES (3,'USER3');
INSERT INTO user (ID,FIRST_NAME) VALUES (4,'USER4');
INSERT INTO user (ID,FIRST_NAME) VALUES (5,'USER5');
INSERT INTO user (ID,FIRST_NAME) VALUES (6,'USER6');