INSERT INTO event_type (ID,NAME) VALUES (1,'EVENT_TYPE1');
INSERT INTO event_type (ID,NAME) VALUES (2,'EVENT_TYPE2');
INSERT INTO event_type (ID,NAME) VALUES (3,'EVENT_TYPE3');
INSERT INTO event_type (ID,NAME) VALUES (4,'EVENT_TYPE4');
INSERT INTO event_type (ID,NAME) VALUES (5,'EVENT_TYPE5');
INSERT INTO event_type (ID,NAME) VALUES (6,'EVENT_TYPE6');