--RESETTING AUTO-INCREMENT
ALTER TABLE calendardbtest.events AUTO_INCREMENT = 100000;
ALTER TABLE calendardbtest.event_types AUTO_INCREMENT = 100000;
ALTER TABLE calendardbtest.users AUTO_INCREMENT = 100000;
--FILLING DB WITH DATA

--USER_ROLES
INSERT INTO calendardbtest.user_roles (ID, NAME) VALUES (1,'USER_ROLE1');
INSERT INTO calendardbtest.user_roles (ID, NAME) VALUES (2,'USER_ROLE2');
INSERT INTO calendardbtest.user_roles (ID, NAME) VALUES (3,'USER_ROLE3');
--DONT ADD USER_ROLE4
--DONT ADD USER_ROLE5 TO ANY USER
INSERT INTO calendardbtest.user_roles (ID, NAME) VALUES (5,'USER_ROLE5');
--DONT ADD USER5 TO ANY EVENT

--USERS
INSERT INTO calendardbtest.users (ID,FIRST_NAME,LAST_NAME,EMAIL,USERNAME,PASSWORD,USER_ROLES_ID)VALUES (1,'USER1','USEROV1','USER1@email.com','USERNAME1','USER1PASSWORD',1);
INSERT INTO calendardbtest.users (ID,FIRST_NAME,LAST_NAME,EMAIL,USERNAME,PASSWORD,USER_ROLES_ID)VALUES (2,'USER2','USEROV2','USER2@email.com','USERNAME2','USER2PASSWORD',1);
INSERT INTO calendardbtest.users (ID,FIRST_NAME,LAST_NAME,EMAIL,USERNAME,PASSWORD,USER_ROLES_ID)VALUES (3,'USER3','USEROV3','USER3@email.com','USERNAME3','USER3PASSWORD',1);
--DONT ADD USER4
--DONT ADD USER5 TO ANY EVENT
INSERT INTO calendardbtest.users (ID,FIRST_NAME,LAST_NAME,EMAIL,USERNAME,PASSWORD,USER_ROLES_ID)VALUES (5,'USER5','USEROV5','USER5@email.com','USERNAME5','USER5PASSWORD',1);
--DONT ADD USER5 TO ANY EVENT

--EVENT_TYPES
INSERT INTO calendardbtest.event_types (ID,NAME, INFO) VALUES (1,'EVENT_TYPE1','EVENT_TYPE1_INFO');
INSERT INTO calendardbtest.event_types (ID,NAME, INFO) VALUES (2,'EVENT_TYPE2','EVENT_TYPE2_INFO');
INSERT INTO calendardbtest.event_types (ID,NAME, INFO) VALUES (3,'EVENT_TYPE3','EVENT_TYPE3_INFO');
--DONT ADD EVENT_TYPE4
--DONT ADD EVENT_TYPE5 TO ANY EVENT
INSERT INTO calendardbtest.event_types (ID,NAME, INFO) VALUES (5,'EVENT_TYPE5','EVENT_TYPE5_INFO');
--DONT ADD EVENT_TYPE5 TO ANY EVENT

--EVENTS
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (1,'EVENT1',1,2);
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (2,'EVENT2',2,3);
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (3,'EVENT3',3,1);
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (4,'EVENT4',1,3);
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (5,'EVENT5',2,2);
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (6,'EVENT6',3,1);
--DONT ADD EVENT7
INSERT INTO calendardbtest.events (ID,NAME,USER_ID,EVENT_TYPE_ID) VALUES (8,'EVENT8',3,1);